#define rsvd  "Reserved"                //must be macro to be coalesced          
const char * const EV_Info_Codes[] = {  "Depricated_Unspecified",                // 0       
                                        "Depricated_StStatusOp_not_ready",       // 1       
                                        "Depricated_EV_Energy_Management_Fault", // 2       
                                        "Depricated_User_Stop",                  // 3       
                                        "Depricated_Maximum_current_too_low",    // 4       
                                        rsvd,                                    // 5       
                                        rsvd,                                    // 6       
                                        rsvd,                                    // 7       
                                        rsvd,                                    // 8       
                                        rsvd,                                    // 9       
                                        rsvd,                                    // A       
                                        rsvd,                                    // B       
                                        rsvd,                                    // C       
                                        rsvd,                                    // D       
                                        rsvd,                                    // E       
                                        rsvd,                                    // F       
                                        rsvd,                                    // 10      
                                        "Version_fails",                         // 11      
                                        "Initialization_fails",                  // 12      
                                        "Version_Restart",                       // 13      
                                        "Bit_Rate_Restart",                      // 14      
                                        "MCU_Reset_Restart",                     // 15      
                                        "Pilot_Fault_Restart",                   // 16      
                                        "No_LIN",                                // 17      
                                        "Int_Fault_Restart",                     // 18      
                                        "Int_Fault_Termination",                 // 19      
                                        "Available_current_too_low",             // 1A      
                                        "Available_voltage_too_high",            // 1B      
                                        "Frequency_Mismatch",                    // 1C      
                                        "EMS_Charging_delayed",                  // 1D      
                                        "Isolation_fault",                       // 1E      
                                        "Charging_Delayed",                      // 1F      
                                        "Interrupt_Clean",                       // 20      
                                        "Interrupt_Dirty",                       // 21      
                                        "Available_voltage_too_low",             // 22      
                                        rsvd,                                    // 23      
                                        rsvd,                                    // 24      
                                        rsvd,                                    // 25      
                                        rsvd,                                    // 26      
                                        rsvd,                                    // 27      
                                        rsvd,                                    // 28      
                                        rsvd,                                    // 29      
                                        rsvd,                                    // 2A      
                                        rsvd,                                    // 2B      
                                        rsvd,                                    // 2C      
                                        rsvd,                                    // 2D      
                                        rsvd,                                    // 2E      
                                        rsvd,                                    // 2F      
                                        rsvd,                                    // 30      
                                        rsvd,                                    // 31      
                                        rsvd,                                    // 32      
                                        rsvd,                                    // 33      
                                        rsvd,                                    // 34      
                                        rsvd,                                    // 35      
                                        rsvd,                                    // 36      
                                        rsvd,                                    // 37      
                                        rsvd,                                    // 38      
                                        rsvd,                                    // 39      
                                        rsvd,                                    // 3A      
                                        rsvd,                                    // 3B      
                                        rsvd,                                    // 3C      
                                        rsvd,                                    // 3D      
                                        rsvd,                                    // 3E      
                                        rsvd,                                    // 3F      
                                        rsvd,                                    // 40      
                                        rsvd,                                    // 41      
                                        rsvd,                                    // 42      
                                        rsvd,                                    // 43      
                                        rsvd,                                    // 44      
                                        rsvd,                                    // 45      
                                        rsvd,                                    // 46      
                                        rsvd,                                    // 47      
                                        rsvd,                                    // 48      
                                        rsvd,                                    // 49      
                                        rsvd,                                    // 4A      
                                        rsvd,                                    // 4B      
                                        rsvd,                                    // 4C      
                                        rsvd,                                    // 4D      
                                        rsvd,                                    // 4E      
                                        rsvd,                                    // 4F      
                                        rsvd,                                    // 50      
                                        rsvd,                                    // 51      
                                        rsvd,                                    // 52      
                                        rsvd,                                    // 53      
                                        rsvd,                                    // 54      
                                        rsvd,                                    // 55      
                                        rsvd,                                    // 56      
                                        rsvd,                                    // 57      
                                        rsvd,                                    // 58      
                                        rsvd,                                    // 59      
                                        rsvd,                                    // 5A      
                                        rsvd,                                    // 5B      
                                        rsvd,                                    // 5C      
                                        rsvd,                                    // 5D      
                                        rsvd,                                    // 5E      
                                        rsvd,                                    // 5F      
                                        rsvd,                                    // 60      
                                        rsvd,                                    // 61      
                                        rsvd,                                    // 62      
                                        rsvd,                                    // 63      
                                        rsvd,                                    // 64      
                                        rsvd,                                    // 65      
                                        rsvd,                                    // 66      
                                        rsvd,                                    // 67      
                                        rsvd,                                    // 68      
                                        rsvd,                                    // 69      
                                        rsvd,                                    // 6A      
                                        rsvd,                                    // 6B      
                                        rsvd,                                    // 6C      
                                        rsvd,                                    // 6D      
                                        rsvd,                                    // 6E      
                                        rsvd,                                    // 6F      
                                        rsvd,                                    // 70      
                                        rsvd,                                    // 71      
                                        rsvd,                                    // 72      
                                        rsvd,                                    // 73      
                                        rsvd,                                    // 74      
                                        rsvd,                                    // 75      
                                        rsvd,                                    // 76      
                                        rsvd,                                    // 77      
                                        rsvd,                                    // 78      
                                        rsvd,                                    // 79      
                                        rsvd,                                    // 7A      
                                        rsvd,                                    // 7B      
                                        rsvd,                                    // 7C      
                                        rsvd,                                    // 7D      
                                        rsvd,                                    // 7E      
                                        rsvd,                                    // 7F      
                                        rsvd,                                    // 80      
                                        rsvd,                                    // 81      
                                        rsvd,                                    // 82      
                                        rsvd,                                    // 83      
                                        rsvd,                                    // 84      
                                        rsvd,                                    // 85      
                                        rsvd,                                    // 86      
                                        rsvd,                                    // 87      
                                        rsvd,                                    // 88      
                                        rsvd,                                    // 89      
                                        rsvd,                                    // 8A      
                                        rsvd,                                    // 8B      
                                        rsvd,                                    // 8C      
                                        rsvd,                                    // 8D      
                                        rsvd,                                    // 8E      
                                        rsvd,                                    // 8F      
                                        rsvd,                                    // 90      
                                        rsvd,                                    // 91      
                                        rsvd,                                    // 92      
                                        rsvd,                                    // 93      
                                        rsvd,                                    // 94      
                                        rsvd,                                    // 95      
                                        rsvd,                                    // 96      
                                        rsvd,                                    // 97      
                                        rsvd,                                    // 98      
                                        rsvd,                                    // 99      
                                        rsvd,                                    // 9A      
                                        rsvd,                                    // 9B      
                                        rsvd,                                    // 9C      
                                        rsvd,                                    // 9D      
                                        rsvd,                                    // 9E      
                                        rsvd,                                    // 9F      
                                        rsvd,                                    // A0      
                                        rsvd,                                    // A1      
                                        rsvd,                                    // A2      
                                        rsvd,                                    // A3      
                                        rsvd,                                    // A4      
                                        rsvd,                                    // A5      
                                        rsvd,                                    // A6      
                                        rsvd,                                    // A7      
                                        rsvd,                                    // A8      
                                        rsvd,                                    // A9      
                                        rsvd,                                    // AA      
                                        rsvd,                                    // AB      
                                        rsvd,                                    // AC      
                                        rsvd,                                    // AD      
                                        rsvd,                                    // AE      
                                        rsvd,                                    // AF      
                                        rsvd,                                    // B0      
                                        rsvd,                                    // B1      
                                        rsvd,                                    // B2      
                                        rsvd,                                    // B3      
                                        rsvd,                                    // B4      
                                        rsvd,                                    // B5      
                                        rsvd,                                    // B6      
                                        rsvd,                                    // B7      
                                        rsvd,                                    // B8      
                                        rsvd,                                    // B9      
                                        rsvd,                                    // BA      
                                        rsvd,                                    // BB      
                                        rsvd,                                    // BC      
                                        rsvd,                                    // BD      
                                        rsvd,                                    // BE      
                                        rsvd,                                    // BF      
                                        rsvd,                                    // C0      
                                        rsvd,                                    // C1      
                                        rsvd,                                    // C2      
                                        rsvd,                                    // C3      
                                        rsvd,                                    // C4      
                                        rsvd,                                    // C5      
                                        rsvd,                                    // C6      
                                        rsvd,                                    // C7      
                                        rsvd,                                    // C8      
                                        rsvd,                                    // C9      
                                        rsvd,                                    // CA      
                                        rsvd,                                    // CB      
                                        rsvd,                                    // CC      
                                        rsvd,                                    // CD      
                                        rsvd,                                    // CE      
                                        rsvd,                                    // CF      
                                        rsvd,                                    // D0      
                                        rsvd,                                    // D1      
                                        rsvd,                                    // D2      
                                        rsvd,                                    // D3      
                                        rsvd,                                    // D4      
                                        rsvd,                                    // D5      
                                        rsvd,                                    // D6      
                                        rsvd,                                    // D7      
                                        rsvd,                                    // D8      
                                        rsvd,                                    // D9      
                                        rsvd,                                    // DA      
                                        rsvd,                                    // DB      
                                        rsvd,                                    // DC      
                                        rsvd,                                    // DD      
                                        rsvd,                                    // DE      
                                        rsvd,                                    // DF      
                                        rsvd,                                    // E0      
                                        rsvd,                                    // E1      
                                        rsvd,                                    // E2      
                                        rsvd,                                    // E3      
                                        rsvd,                                    // E4      
                                        rsvd,                                    // E5      
                                        rsvd,                                    // E6      
                                        rsvd,                                    // E7      
                                        rsvd,                                    // E8      
                                        rsvd,                                    // E9      
                                        rsvd,                                    // EA      
                                        rsvd,                                    // EB      
                                        rsvd,                                    // EC      
                                        rsvd,                                    // ED      
                                        rsvd,                                    // EE      
                                        rsvd,                                    // EF      
                                        rsvd,                                    // F0      
                                        rsvd,                                    // F1      
                                        rsvd,                                    // F2      
                                        rsvd,                                    // F3      
                                        rsvd,                                    // F4      
                                        rsvd,                                    // F5      
                                        rsvd,                                    // F6      
                                        rsvd,                                    // F7      
                                        rsvd,                                    // F8      
                                        rsvd,                                    // F9      
                                        rsvd,                                    // FA      
                                        rsvd,                                    // FB      
                                        rsvd,                                    // FC      
                                        rsvd,                                    // FD      
                                        rsvd,                                    // FE      
                                        "Empty",                                 // FF      
                                        };                                       
const char * const SE_Info_Codes[] = {  "Depricated_Unspecified",                // 0       
                                        "Depricated_sleep",                      // 1       
                                        "Depricated_Energy_Unavailable",         // 2       
                                        "Depricated_User_Stop",                  // 3       
                                        rsvd,                                    // 4       
                                        rsvd,                                    // 5       
                                        rsvd,                                    // 6       
                                        rsvd,                                    // 7       
                                        rsvd,                                    // 8       
                                        rsvd,                                    // 9       
                                        rsvd,                                    // A       
                                        rsvd,                                    // B       
                                        rsvd,                                    // C       
                                        rsvd,                                    // D       
                                        rsvd,                                    // E       
                                        rsvd,                                    // F       
                                        rsvd,                                    // 10      
                                        "Version_fails",                         // 11      
                                        "Initialization_fails",                  // 12      
                                        "Version_Restart",                       // 13      
                                        "Bit_Rate_Restart",                      // 14      
                                        "MCU_Reset_Restart",                     // 15      
                                        "Power_Fault_Restart",                   // 16      
                                        "No_LIN",                                // 17      
                                        "Int_Fault_Restart",                     // 18      
                                        "EMS_Charging_delayed",                  // 19      
                                        "User_Stop",                             // 1A      
                                        "Available_current_too_low",             // 1B      
                                        "Available_voltage_too_high",            // 1C      
                                        "Frequency_Mismatch",                    // 1D      
                                        "Init_timeout",                          // 1E      
                                        "Connector_Over_Temp",                   // 1F      
                                        "Over_Temp",                             // 20      
                                        "Temp_Sense_Invalid",                    // 21      
                                        "Overcurrent",                           // 22      
                                        "Current_Sense_Invalid",                 // 23      
                                        "Voltage_Sense_Invalid",                 // 24      
                                        "Pilot_fault",                           // 25      
                                        "Contactor_fault",                       // 26      
                                        "Input_miswired",                        // 27      
                                        "Input_over_voltage",                    // 28      
                                        "Input_under_voltage",                   // 29      
                                        "CCID_self_test_fault",                  // 2A      
                                        "CCID_tripped_retry",                    // 2B      
                                        "CCID_tripped_no_retry",                 // 2C      
                                        "Breaker_tripped",                       // 2D      
                                        "Ground_Monitor_fault",                  // 2E      
                                        "Configuration_error",                   // 2F      
                                        "Ground_fault",                          // 30      
                                        "Comm_Fault",                            // 31      
                                        "Internal_Fault",                        // 32      
                                        "Available_voltage_too_low",             // 33      
                                        rsvd,                                    // 34      
                                        rsvd,                                    // 35      
                                        rsvd,                                    // 36      
                                        rsvd,                                    // 37      
                                        rsvd,                                    // 38      
                                        rsvd,                                    // 39      
                                        rsvd,                                    // 3A      
                                        rsvd,                                    // 3B      
                                        rsvd,                                    // 3C      
                                        rsvd,                                    // 3D      
                                        rsvd,                                    // 3E      
                                        rsvd,                                    // 3F      
                                        rsvd,                                    // 40      
                                        rsvd,                                    // 41      
                                        rsvd,                                    // 42      
                                        rsvd,                                    // 43      
                                        rsvd,                                    // 44      
                                        rsvd,                                    // 45      
                                        rsvd,                                    // 46      
                                        rsvd,                                    // 47      
                                        rsvd,                                    // 48      
                                        rsvd,                                    // 49      
                                        rsvd,                                    // 4A      
                                        rsvd,                                    // 4B      
                                        rsvd,                                    // 4C      
                                        rsvd,                                    // 4D      
                                        rsvd,                                    // 4E      
                                        rsvd,                                    // 4F      
                                        rsvd,                                    // 50      
                                        rsvd,                                    // 51      
                                        rsvd,                                    // 52      
                                        rsvd,                                    // 53      
                                        rsvd,                                    // 54      
                                        rsvd,                                    // 55      
                                        rsvd,                                    // 56      
                                        rsvd,                                    // 57      
                                        rsvd,                                    // 58      
                                        rsvd,                                    // 59      
                                        rsvd,                                    // 5A      
                                        rsvd,                                    // 5B      
                                        rsvd,                                    // 5C      
                                        rsvd,                                    // 5D      
                                        rsvd,                                    // 5E      
                                        rsvd,                                    // 5F      
                                        rsvd,                                    // 60      
                                        rsvd,                                    // 61      
                                        rsvd,                                    // 62      
                                        rsvd,                                    // 63      
                                        rsvd,                                    // 64      
                                        rsvd,                                    // 65      
                                        rsvd,                                    // 66      
                                        rsvd,                                    // 67      
                                        rsvd,                                    // 68      
                                        rsvd,                                    // 69      
                                        rsvd,                                    // 6A      
                                        rsvd,                                    // 6B      
                                        rsvd,                                    // 6C      
                                        rsvd,                                    // 6D      
                                        rsvd,                                    // 6E      
                                        rsvd,                                    // 6F      
                                        rsvd,                                    // 70      
                                        rsvd,                                    // 71      
                                        rsvd,                                    // 72      
                                        rsvd,                                    // 73      
                                        rsvd,                                    // 74      
                                        rsvd,                                    // 75      
                                        rsvd,                                    // 76      
                                        rsvd,                                    // 77      
                                        rsvd,                                    // 78      
                                        rsvd,                                    // 79      
                                        rsvd,                                    // 7A      
                                        rsvd,                                    // 7B      
                                        rsvd,                                    // 7C      
                                        rsvd,                                    // 7D      
                                        rsvd,                                    // 7E      
                                        rsvd,                                    // 7F      
                                        rsvd,                                    // 80      
                                        rsvd,                                    // 81      
                                        rsvd,                                    // 82      
                                        rsvd,                                    // 83      
                                        rsvd,                                    // 84      
                                        rsvd,                                    // 85      
                                        rsvd,                                    // 86      
                                        rsvd,                                    // 87      
                                        rsvd,                                    // 88      
                                        rsvd,                                    // 89      
                                        rsvd,                                    // 8A      
                                        rsvd,                                    // 8B      
                                        rsvd,                                    // 8C      
                                        rsvd,                                    // 8D      
                                        rsvd,                                    // 8E      
                                        rsvd,                                    // 8F      
                                        rsvd,                                    // 90      
                                        rsvd,                                    // 91      
                                        rsvd,                                    // 92      
                                        rsvd,                                    // 93      
                                        rsvd,                                    // 94      
                                        rsvd,                                    // 95      
                                        rsvd,                                    // 96      
                                        rsvd,                                    // 97      
                                        rsvd,                                    // 98      
                                        rsvd,                                    // 99      
                                        rsvd,                                    // 9A      
                                        rsvd,                                    // 9B      
                                        rsvd,                                    // 9C      
                                        rsvd,                                    // 9D      
                                        rsvd,                                    // 9E      
                                        rsvd,                                    // 9F      
                                        rsvd,                                    // A0      
                                        rsvd,                                    // A1      
                                        rsvd,                                    // A2      
                                        rsvd,                                    // A3      
                                        rsvd,                                    // A4      
                                        rsvd,                                    // A5      
                                        rsvd,                                    // A6      
                                        rsvd,                                    // A7      
                                        rsvd,                                    // A8      
                                        rsvd,                                    // A9      
                                        rsvd,                                    // AA      
                                        rsvd,                                    // AB      
                                        rsvd,                                    // AC      
                                        rsvd,                                    // AD      
                                        rsvd,                                    // AE      
                                        rsvd,                                    // AF      
                                        rsvd,                                    // B0      
                                        rsvd,                                    // B1      
                                        rsvd,                                    // B2      
                                        rsvd,                                    // B3      
                                        rsvd,                                    // B4      
                                        rsvd,                                    // B5      
                                        rsvd,                                    // B6      
                                        rsvd,                                    // B7      
                                        rsvd,                                    // B8      
                                        rsvd,                                    // B9      
                                        rsvd,                                    // BA      
                                        rsvd,                                    // BB      
                                        rsvd,                                    // BC      
                                        rsvd,                                    // BD      
                                        rsvd,                                    // BE      
                                        rsvd,                                    // BF      
                                        rsvd,                                    // C0      
                                        rsvd,                                    // C1      
                                        rsvd,                                    // C2      
                                        rsvd,                                    // C3      
                                        rsvd,                                    // C4      
                                        rsvd,                                    // C5      
                                        rsvd,                                    // C6      
                                        rsvd,                                    // C7      
                                        rsvd,                                    // C8      
                                        rsvd,                                    // C9      
                                        rsvd,                                    // CA      
                                        rsvd,                                    // CB      
                                        rsvd,                                    // CC      
                                        rsvd,                                    // CD      
                                        rsvd,                                    // CE      
                                        rsvd,                                    // CF      
                                        rsvd,                                    // D0      
                                        rsvd,                                    // D1      
                                        rsvd,                                    // D2      
                                        rsvd,                                    // D3      
                                        rsvd,                                    // D4      
                                        rsvd,                                    // D5      
                                        rsvd,                                    // D6      
                                        rsvd,                                    // D7      
                                        rsvd,                                    // D8      
                                        rsvd,                                    // D9      
                                        rsvd,                                    // DA      
                                        rsvd,                                    // DB      
                                        rsvd,                                    // DC      
                                        rsvd,                                    // DD      
                                        rsvd,                                    // DE      
                                        rsvd,                                    // DF      
                                        rsvd,                                    // E0      
                                        rsvd,                                    // E1      
                                        rsvd,                                    // E2      
                                        rsvd,                                    // E3      
                                        rsvd,                                    // E4      
                                        rsvd,                                    // E5      
                                        rsvd,                                    // E6      
                                        rsvd,                                    // E7      
                                        rsvd,                                    // E8      
                                        rsvd,                                    // E9      
                                        rsvd,                                    // EA      
                                        rsvd,                                    // EB      
                                        rsvd,                                    // EC      
                                        rsvd,                                    // ED      
                                        rsvd,                                    // EE      
                                        rsvd,                                    // EF      
                                        rsvd,                                    // F0      
                                        rsvd,                                    // F1      
                                        rsvd,                                    // F2      
                                        rsvd,                                    // F3      
                                        rsvd,                                    // F4      
                                        rsvd,                                    // F5      
                                        rsvd,                                    // F6      
                                        rsvd,                                    // F7      
                                        rsvd,                                    // F8      
                                        rsvd,                                    // F9      
                                        rsvd,                                    // FA      
                                        rsvd,                                    // FB      
                                        rsvd,                                    // FC      
                                        rsvd,                                    // FD      
                                        rsvd,                                    // FE      
                                        "Empty",                                 // FF      
                                        };                                       
